export const fr_es = {
    fr: {
        site_title: "Lettres de Calvin",
        search: "Rechercher",
        txt_ppt : "Cette édition critique numérique bilingue présente les lettres écrites en français par Jean Calvin entre 1538 et 1554. Elle propose une transcription modernisée, des annotations, ainsi qu’une traduction en espagnol. \n Pensée comme une plateforme dynamique de recherche, l’édition s’inscrit dans une démarche d’exploration des pratiques éditoriales à l’ère numérique. Elle mobilise des outils algorithmiques pour interroger la transmission des textes, le rôle du geste éditorial, et la réception contemporaine de la pensée calvinienne.",
        txt_temp: "L'édition est encore en cours de développement. De nouveau contenu et des lettres seront ajoutées prochainement.",
        home: "Accueil",
        calvin : "Jean Calvin",
        lettres : "Lettres",
        preface: "Préface par Jules Bonnet (1854)",
        onCalvin: "Vie et œuvre",
        context: "Contexte historique",
        names: "Personnes",
        places: "Lieux",
        letters: "Lettres françaises",
        research: "Recherche",
        about: "À propos",
        //href_about: "/a_propos",
        contact: "Contact",
        tag_cloud: "Nuage de thèmes",
        theme : "Thème",
        categories: "Catégories",
        category : "Catégorie",
        cat_nature: "NATURE DU DOCUMENT SOURCE",
        copy: "COPIE",
        //href_copy: "/categories/copie",
        orig_autograph: "ORIG. AUTOGRAPHE",
        //href_orig_autograph: "/categories/orig-autographe",
        orig: "ORIGINAL",
        //href_orig: "/categories/original",
        minute_orig: "MINUTE ORIGINALE",
        //href_minute_orig: "/categories/minute-originale",
        minute_autog: "MINUTE AUTOGRAPHE",
        //href_minute_autog: "/categories/minute-autographe",
        cat_recipient: "DESTINATAIRES",
        individual: "INDIVIDU",
        //href_individual: "/categories/individu",
        group: "COLLECTIVITÉ",
        //href_group: "/categories/collectivite",
        cat_signature: "SIGNATURE ",
        signed_many: "SIGNÉE PAR PLUSIEURS",
        //href_signed_many: "/categories/signee-par-plusieurs",
        pseudonym: "SOUS PSEUDONYME",
        //href_pseudonym: "/categories/sous-pseudonyme",
        no_signature: "SANS SIGNATURE",
        //href_no_signature: "/categories/sans-signature",
        timeline : "Frise Chronologique",
        timeline_text : "Lettres par ordre chronologique",
        policies: "Mentions légales",
        edition: "Édition de Yanet Hernández Pedraza",
        m_error: "La page n'a pas été trouvée.",
        name_index: "Index de noms",
        name_carte: "Index de lieux",
        name_notes : "Les informations ont été directement tirées de Wikidata, sauf indication contraire.",
       portrait_text : "Portrait de",
        href_letters : "fr/lettres",
        ppt_index: "Vous pouvez également explorer la correspondance par :",
        savoirplus: "En savoir plus",
        misajour: "Dernière mise à jour : 17 mai 2025"
    },
    es: {
        site_title: "Cartas de Calvino",
        search: "Buscar",
        txt_ppt : "Esta edición crítica digital bilingüe presenta las cartas escritas en francés por Juan Calvino entre 1538 y 1554. Ofrece una transcripción modernizada, anotaciones y una traducción al español. \n Concebida como una plataforma dinámica de investigación, la edición se inscribe en una reflexión sobre las prácticas editoriales en la era digital. Recurre a herramientas algorítmicas para interrogar la transmisión de los textos, el papel del gesto editorial y la recepción contemporánea del pensamiento calvinista.",
        txt_temp: "La edición aún está en desarrollo. Pronto se añadirán nuevos contenidos y cartas.",
        home: "Página de inicio",
        calvin : "Juan Calvino",
        lettres : "Cartas",
        preface: "Prefacio de Jules Bonnet (1854)",
        onCalvin: "Vida y obra",
        context: "Contexto histórico",
        names: "Personas",
        places: "Lugares",
        letters: "Cartas francesas",
        research: "Investigación",
        about: "Acerca de",
        //href_about: "/a_propos_es",
        contact: "Contacto",
        tag_cloud: "Nube de temas",
        theme : "Tema",
        categories: "Categorías",
        category : "Categoría",
        cat_nature: "TIPO DE DOCUMENTO FUENTE",
        copy: "COPIA",
        //href_copy: "/categories/copia",
        orig_autograph: "AUTÓGRAFO ORIGINAL",
        //href_orig_autograph: "/categories/autografo_orig",
        orig: "ORIGINAL",
        //href_orig: "/categories/originales",
        minute_orig: "MINUTA ORIGINAL",
        //href_minute_orig: "/categories/minuta-original",
        minute_autog: "MINUTA AUTÓGRAFA",
        //href_minute_autog: "/categories/minuta-autografa",
        cat_recipient: "DESTINATARIO",
        individual: "INDIVIDUO",
        //href_individual: "/categories/individuo",
        group: "GRUPO",
        //href_group: "/categories/grupo",
        cat_signature: "FIRMA ",
        signed_many: "FIRMADA POR VARIOS",
        //href_signed_many: "/categories/firmada_varios",
        pseudonym: "BAJO PSEUDÓNIMO",
        //href_pseudonym: "/categories/bajo-pseudonimo",
        no_signature: "SIN FIRMA",
        //href_no_signature: "/categories/sin-firma",
        timeline : "Línea de tiempo",
        timeline_text : "Cartas en orden cronológico",
        policies: "Aviso legal",
        edition: "Edición de Yanet Hernández Pedraza",
        m_error: "Esta página no existe.",
        name_index: "Índice de personas",
        name_carte: "Índice de lugares",
        name_notes : "Las informaciones provienen directamente de Wikidata, salvo indicación contraria.",
        portrait_text : "Retrato de",
        href_letters : "es/cartas",
        ppt_index: "También puede explorar la correspondencia por:",
        savoirplus: "Más información",
        misajour: "Última actualización : 17 mayo de 2025"
    }
}