export const fr_es = {
    fr: {
        site_title: "Lettres de Calvin",
        search: "Rechercher",
        txt_ppt : "Cette édition critique numérique bilingue présente les lettres écrites en français par Jean Calvin entre 1538 et 1554. Elle propose une transcription modernisée, des annotations, ainsi qu’une traduction en espagnol. \n Pensée comme une infrastructure dynamique de recherche, l’édition s’inscrit dans une démarche d’exploration des pratiques éditoriales à l’ère numérique. Elle mobilise des outils algorithmiques pour interroger la transmission des textes, le rôle du geste éditorial, et la réception contemporaine de la pensée calvinienne.",
        txt_temp: "L'édition est encore en cours de développement. De nouveau contenu et des lettres seront ajoutées prochainement.",
        home: "Accueil",
        keywords: "Jean Calvin, lettres, correspondance, Réforme protestante, XVIe siècle, histoire, religion, théologie, édition, manuscrits anciens, transcriptions, réseau de correspondance",
        calvin : "Jean Calvin",
        lettres : "Lettres",
        preface: "Préface par Jules Bonnet (1854)",
        onCalvin: "Vie et œuvre",
        context: "Contexte historique",
        names: "Personnes",
        places: "Lieux",
        letters: "Lettres françaises",
        research: "Recherche",
        about: "À propos",
        //href_about: "/a_propos",
        contact: "Contact",
        tag_cloud: "Nuage de thèmes",
        theme : "Thème",
        categories: "Catégories",
        category : "Catégorie",
        cat_nature: "NATURE DU DOCUMENT SOURCE",
        copy: "COPIE",
        //href_copy: "/categories/copie",
        orig_autograph: "ORIG. AUTOGRAPHE",
        //href_orig_autograph: "/categories/orig-autographe",
        orig: "ORIGINAL",
        //href_orig: "/categories/original",
        minute_orig: "MINUTE ORIGINALE",
        //href_minute_orig: "/categories/minute-originale",
        minute_autog: "MINUTE AUTOGRAPHE",
        //href_minute_autog: "/categories/minute-autographe",
        cat_recipient: "DESTINATAIRES",
        individual: "INDIVIDU",
        //href_individual: "/categories/individu",
        group: "COLLECTIVITÉ",
        //href_group: "/categories/collectivite",
        cat_signature: "SIGNATURE ",
        signed_many: "SIGNÉE PAR PLUSIEURS",
        //href_signed_many: "/categories/signee-par-plusieurs",
        pseudonym: "SOUS PSEUDONYME",
        //href_pseudonym: "/categories/sous-pseudonyme",
        no_signature: "SANS SIGNATURE",
        //href_no_signature: "/categories/sans-signature",
        timeline : "Frise Chronologique",
        timeline_text : "Lettres par ordre chronologique",
        policies: "Mentions légales",
        edition: "Édition de Yanet Hernández Pedraza",
        m_error: "La page n'a pas été trouvée.",
        name_index: "Index de noms",
        names_desc: "Index de destinataires et de personnes mentionnées dans les lettres de Calvin (1538-1554).",
        name_carte: "Index de lieux",
        carte_desc:"Carte interactive du réseau de la correspondance de Calvin (1538-1554) montrant autant la dimension géographique que les dimensions relationnelle et temporelle de son activité épistolaire.",
        name_notes : "Les informations ont été directement tirées de Wikidata, sauf indication contraire.",
       portrait_text : "Portrait de",
        href_letters : "fr/lettres",
        ppt_index: "Vous pouvez également explorer la correspondance par :",
        savoirplus: "En savoir plus",
        pdfs_header: "Générateur de sorties PDF",
        pdfs_p: "Cette fonctionnalité a été conçue pour filtrer trnasversalement les lettres de Calvin d'après différents critères basées sur les index de la présente édition numérique. La langue du PDF sera celle de l'interface (français ou espagnol). La sélection des critères sera sauvegardée et utilisée pour analyser les intérêts des lecteurs modernes concernant Jean Calvin.\n NOTE : Il s'agit d'un outil de génération de PDF en développement. Il est recommandé d'attendre quelques secondes après avoir cliqué sur le bouton de génération pour permettre au contenu de charger complètement avant d'imprimer. N'hésitez pas à me contacter si vous avez des questions ou des suggestions.",
        pdf_btn_generate: "Générer le PDF",
        pdf_btn_filtres: "Appliquer filtres",
        txt_filtrer : "Filtrer transversalement",
        txt_all: "Toutes",
        filter_categories:{nature: "Nature du document source", recipient: "Destinataire(s)", signature: "Signature", theme: "Thématique", period: "Période", srcPlace: "Lieu d'origine", destPlace: "Lieu de destination", searchFilter: "Terme de recherche"},
        pdf_title : "Lettres de Calvin",
        pdf_subtitle: "Édition critique numérique des lettres françaises de Jean Calvin entre 1538 et 1554",
        pdf_author: "Édition \nde\n Yanet Hernández Pedraza",
        noteStment: `Les notes proviennent de l'édition de Jules Bonnet de 1854 sauf indication contraire. Les notes appelées "éditoriales" (en vert) ainsi que les notes des phrases latines ont été produites par l'auteure de ce projet : Yanet Hernández Pedraza.`,
        text_filtres: "Collection de lettres générée d'après les filtres suivants :",
        pdf_table_cont: "Table des matières",
        warning_browser : "Votre navigateur peut avoir des problèmes pour bien générer le PDF pour 15 lettres ou plus. Il est recommandé d'utiliser Safari ou Firefox.",
        misajour: "Dernière mise à jour : 27 février 2026"
    },
    es: {
        site_title: "Cartas de Calvino",
        search: "Buscar",
        txt_ppt : "Esta edición crítica digital bilingüe presenta las cartas escritas en francés por Juan Calvino entre 1538 y 1554. Ofrece una transcripción modernizada, anotaciones y una traducción al español. \n Concebida como una infraestructura dinámica de investigación, la edición se inscribe en una reflexión sobre las prácticas editoriales en la era digital. Recurre a herramientas algorítmicas para interrogar la transmisión de los textos, el papel del gesto editorial y la recepción contemporánea del pensamiento calvinista.",
        txt_temp: "La edición aún está en desarrollo. Pronto se añadirán nuevos contenidos y cartas.",
        home: "Página de inicio",
        keywords: "Juan Calvino, cartas, correspondencia, Reforma protestante, siglo XVI, historia, religión, teología, edición, manuscritos antiguos, transcripciones, red de correspondencia",
        calvin : "Juan Calvino",
        lettres : "Cartas",
        preface: "Prefacio de Jules Bonnet (1854)",
        onCalvin: "Vida y obra",
        context: "Contexto histórico",
        names: "Personas",
        places: "Lugares",
        letters: "Cartas francesas",
        research: "Investigación",
        about: "Acerca de",
        //href_about: "/a_propos_es",
        contact: "Contacto",
        tag_cloud: "Nube de temas",
        theme : "Tema",
        categories: "Categorías",
        category : "Categoría",
        cat_nature: "TIPO DE DOCUMENTO FUENTE",
        copy: "COPIA",
        //href_copy: "/categories/copia",
        orig_autograph: "AUTÓGRAFO ORIGINAL",
        //href_orig_autograph: "/categories/autografo_orig",
        orig: "ORIGINAL",
        //href_orig: "/categories/originales",
        minute_orig: "MINUTA ORIGINAL",
        //href_minute_orig: "/categories/minuta-original",
        minute_autog: "MINUTA AUTÓGRAFA",
        //href_minute_autog: "/categories/minuta-autografa",
        cat_recipient: "DESTINATARIO",
        individual: "INDIVIDUO",
        //href_individual: "/categories/individuo",
        group: "GRUPO",
        //href_group: "/categories/grupo",
        cat_signature: "FIRMA ",
        signed_many: "FIRMADA POR VARIOS",
        //href_signed_many: "/categories/firmada_varios",
        pseudonym: "BAJO PSEUDÓNIMO",
        //href_pseudonym: "/categories/bajo-pseudonimo",
        no_signature: "SIN FIRMA",
        //href_no_signature: "/categories/sin-firma",
        timeline : "Línea de tiempo",
        timeline_text : "Cartas en orden cronológico",
        policies: "Aviso legal",
        edition: "Edición de Yanet Hernández Pedraza",
        m_error: "Esta página no existe.",
        name_index: "Índice de personas",
        names_desc: "Índice de destinatarios y de personas mencionadas en las cartas de Calvino (1538-1554).",
        name_carte: "Índice de lugares",
        carte_desc:"Mapa interactivo de la red de la correspondencia de Calvino (1538-1554) que muestra tanto la dimensión geográfica como relacional y temporal de su actividad epistolar.",
        name_notes : "Las informaciones provienen directamente de Wikidata, salvo indicación contraria.",
        portrait_text : "Retrato de",
        href_letters : "es/cartas",
        ppt_index: "También puede explorar la correspondencia por:",
        savoirplus: "Más información",
        pdfs_header: "Generador de PDFs",
        pdfs_p: "Esta funcionalidad está diseñada para filtrar transversalmente las cartas de Calvino de acuerdo a diferentes criterios basados en los índices de la presente edición digital. El idioma del PDF será el de la interface (francés o español). La selección de los criterios se guardará e utilizará para analizar los intereses de los lectores modernos en lo concerniente a Juan Calvino.\n NOTA: Esta es una herramienta de generación de PDF en desarrollo. Se recomienda esperar unos segundos después de hacer clic en el botón de generación para permitir que el contenido se cargue completamente antes de imprimir. No dude en ponerse en contacto si tiene alguna pregunta o sugerencia.",
        pdf_btn_generate: "Generar el PDF",
        pdf_btn_filtres: "Aplicar filtros",
        txt_filtrer : "Filtrar transversalmente",
        txt_all: "Todas",
        filter_categories: {nature: "Tipo de documento fuente", recipient: "Destinatario(s)", signature: "Firma", theme: "Tema", period: "Período", srcPlace: "Lugar de origen", destPlace: "Lugar de destino", searchFilter: "Término de búsqueda"},
        pdf_title : "Cartas de Calvino",
        pdf_subtitle: "Edición crítica digital de las cartas escritas en francés por Juan Calvino entre 1538 y 1554",
        pdf_author: "Edición \nde\n Yanet Hernández Pedraza",
        noteStment: 'Las notas provienen de la edición de Jules Bonnet de 1854 a menos que se indique lo contrario. Las notas bajo la apelación "editoriales" (en verde) y las notas de las citas en latín pertenecen a la autora de este proyecto: Yanet Hernández Pedraza.',
        text_filtres: "Colección de cartas generada según los filtros siguientes:",
        pdf_table_cont: "Tabla de contenidos",
        warning_browser : "Puede que su navegador no genere bien el PDF para 15 cartas o más. Se recomienda usar Safari o Firefox.",
        misajour: "Última actualización : 27 de febrero de 2026"
    }
}